### ISSUE TITLE
Error with FlashMessages

### ISSUE THREAD

**Issue by KonstantinSoelch** [BastianBalthasarBux/tt_address#1]
I've just read in your post, that I can submit Issues here, so here we go:

The Flashmessages Viewhelper throws an error on "List View".

![image](https://user-images.githubusercontent.com/22169163/27476109-bf00befc-5807-11e7-8b78-ea74ebe96a31.png)

I deleted the `renderMode="div"` in `List.html`.

The Typo3 doesn't throw any errors now.

**Comment by BastianBalthasarBux** [comment]
Is this on TYPO3 8.7?

**Comment by KonstantinSoelch** [comment]
yes, Typo3 8.7.2. Should have written that in the Issue my bad.

**Comment by BastianBalthasarBux** [comment]
Fixed in master, thanks for reporting
