### ISSUE TITLE
Error when selecting address record containing a picture

### ISSUE THREAD

**Issue by gregorkuehnert** [BastianBalthasarBux/tt_address#10]
Using TYPO3 v9.5.0 and the current commit, I get an error in the frontend when I select an address record containing a picture. The log shows the following:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1382284106: You must either specify a string src or a File object. | TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file /.../typo3_src/typo3_src-9.5.0/typo3/sysext/fluid/Classes/ViewHelpers/ImageViewHelper.php in line 124.

**Comment by BastianBalthasarBux** [comment]
ATM: We are not able to reproduce that issue ...

**Comment by BastianBalthasarBux** [comment]
Sorry, we can reproduce now ...
