### ISSUE TITLE
Sorting option "singleSelection" has no effect

### ISSUE THREAD

**Issue by gregorkuehnert** [BastianBalthasarBux/tt_address#11]
Using TYPO3 v9.5.0 and the current commit, selecting the sorting option "singleSelection" in flexform has no effect on the sorting of address records in the frontend.

**Comment by BastianBalthasarBux** [comment]
Hmm, i am pretty sure this has nothing to do with 9.5. It is just not implemented ...
But yes, re-thinking it, it may make sense also with manually selected records. And I think it should be easily doable in FLUID ...

**Comment by BastianBalthasarBux** [comment]
Meh. Sorry. My fault. singleRecords sorting is ignored ... :octopus:

**Comment by BastianBalthasarBux** [comment]
Fixed. Feel free to reopen (or simply make a new ticket), if testing is not successfull on your side.
