### ISSUE TITLE
Updater scripts return ajax error in TYPO3 v9

### ISSUE THREAD

**Issue by tillschweneker** [BastianBalthasarBux/tt_address#13]
@BastianBalthasarBux 
The updater script "AddressGroupToSysCategory", "ImageToFileReference" and "TypoScriptTemplateLocation" return AJAX errors, when using the upgrade wizard in TYPO3 v9.

When the extension "typo3db_legacy" is installed the  "AddressGroupToSysCategory" script does what it should do, but returns an error, too. The other scripts don't run at all.

tested with commit 3bcdbd6 and TYPO3 9.5.1-dev

**Comment by BastianBalthasarBux** [comment]
Well, I think the  "AddressGroupToSysCategory" Updater could be removed anyways. It is very outdated.
Same with ImageToFileReference.
But removing them also means, that we need to suggest an upgrade-path.
I will check with Benni (who cares together with me on the upstream code).

**Comment by BastianBalthasarBux** [comment]
Should be resolved with publishing tt_address v4.0.
If there a still problems, please report in the main repository.
Thanks for helping with all the little gizmos! ;)
