### ISSUE TITLE
Partials root path override issue

### ISSUE THREAD

**Issue by heikohaensge** [BastianBalthasarBux/tt_address#6]
Trying to change typoscript constant plugin.tx_ttaddress.view.partialRootPath
to uses custom templates for AddressItemDetail.html and AddressItemList.html fails. 
Any path is ignored and the default templates are used. 
I'm using Typo3 7.6.23
How to override the partial templates?

BTW: Thanks for all the work!

**Comment by BastianBalthasarBux** [comment]
This is connected to issue #5 i think.
ATM i am busy like hell, but i will have a look at it!

**Comment by heikohaensge** [comment]
Hi, since october last year is already a while ago, I'd cautiously like to ask if there is  or will be some progress on the issue?

**Comment by BastianBalthasarBux** [comment]
Yes, there will be progress with the whole thing in Feb. now. Not only this issue, but in general, there are lots of todos ... ;)

**Comment by gregorkuehnert** [comment]
I can confirm this issue for use with v9.5.0. Setting individual template paths via typoscript has no effect.
