### ISSUE TITLE
Doesn't work with TYPO3 8.7.19

### ISSUE THREAD

**Issue by webcande** [BastianBalthasarBux/tt_address#9]
tt_address 3.2.4 works with TYPO3 8.7.19, but version 4.0.0 won't work on same system, PHP version: 7.0.32.

No output in the frontend. Not with legacy static templates or the kind with extbase/fluid. 

I can see the records in the list view in backend, but when I click on one I only see the title of the record
but not one form element. 

The plugin as CE-element can be opened. I also can select there a record and enter it into the select box.

Seems a lot TCA issues.

**Comment by BastianBalthasarBux** [comment]
Ok, so I tried now latest commit of my fork on a 8.7.19 (but with php 7.2.x) and everything works fine with the extbase/fluid Plugin. Can select one or more addresses, these are displayed on the frontend, with list and detail.
If you use legacy plugin CE, you must include the legacy TypoScript, if you use the new extbase/fluid plugin, you need to include the according TypoScript with the static-template section.

Furthermore, did you clear caches and recreate autoloading files via installtool?

**Comment by webcande** [comment]
Thanks!

I startet again. This time on hoster server with PHP version: 	7.2.3

I had a existing TYPO3 8.7.17. Deleted tt_address files in the folder. Then I coppied the NEW files from v4 to here.

And gone through Upgrade Wizard. This was executed: "ALTER TABLE tt_address ADD `sorting` INT DEFAULT 0 NOT NULL, ADD `sys_language_uid` INT DEFAULT 0 NOT NULL, ADD `l10n_parent` INT DEFAULT 0 NOT NULL, ADD `l10n_diffsource` MEDIUMBLOB DEFAULT NULL, ADD `l10n_state` TEXT DEFAULT NULL"

Then on the next step in the Upgrade Wizard regarding the location of the templates I get in Install Tool: "Oops, an error occurred!"

PHP logs say: "Core: Exception handler (WEB): Uncaught TYPO3 Exception: [] operator not supported for strings | Error thrown in file ...ext/tt_address/Classes/Updates/TypoScriptTemplateLocation.php in line 92. Requested URL:  ...&install[action]=upgradeWizard&install[controller]=tool&install[context]=standalone"

I tried to fix that on my own, but seems no luck. I cannot see the Legacy Static Template in Backend but the Extbase/Fluid one. Which is loaded and clearing cache and dump autoloading like every time. 

Can open the records in the backend. Which is a progress!!!!

Now I upgrade to 8.7.19. Still cannot see the output in the frontend.

That is maybe a mismatch to other settings in my system.

**Comment by BastianBalthasarBux** [comment]
ATM I am still struggling with some things, which got mangled to an incomplete merge with upstream (rebase).
I pushed a new version now. In theory, legacy plugin should only be visible, if activated in Extension Manager configuration of tt_address. But ATM this works for the templates, but not for the CE.
Anways, the fluid version should really work now, also on Frontend.
The Error with the updates is strange, I did not touch this part of the code, that's an upstream part, I think by benni.

**Comment by gregorkuehnert** [comment]
I tested the current commit of your fork with v.9.5.0 and got the same result: in the backend everything works as it should, but in the frontend I do not get any output. I use the extbase/fluid-plugin and the corresponding template. Unfortunately, as a pure integrator I can't help technically in this case, but at least wanted to share my test experience. Thank you for your work.

**Comment by BastianBalthasarBux** [comment]
But maybe you could have a look in the logs?

**Comment by gregorkuehnert** [comment]
Of course, you are right. The log shows the following:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Undeclared arguments passed to ViewHelper TYPO3\TtAddress\ViewHelpers\Widget\PaginateViewHelper: objects, as, configuration, initial. Valid arguments are: customWidgetId | TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file /.../typo3_src-9.5.0/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php in line 476.

**Comment by BastianBalthasarBux** [comment]
Cool, thanks. I will investigate. It looks like something is wrong with the pagination viewhelper.
Could you maybe try to test again with as little data that the pagination widget will not get in use?
Meanwhile I will do a test with pagination displayed on v8 LTS. Maybe it is already broken there.

**Comment by gregorkuehnert** [comment]
With only one address selected and/or pagination disabled (hidepagination = 1) the log shows exactly the same error message.

**Comment by BastianBalthasarBux** [comment]
Latest version here should now work with v8 LTS, also with pagination. I think, this solves the problem with the widget viewhelper on TYPO3 v9. Maybe you could test again?

**Comment by gregorkuehnert** [comment]
Now it works fine, even with activated pagination. The frontend output appears, pagination is working and there are no errors in the log. Thank you, good job!

**Comment by BastianBalthasarBux** [comment]
Great! So this could be closed now.
Thanks for your help with testing!
